logging:
  level:
    org.springframework: debug
    com.github.cyberpunkperson.widgetorganizer: debug

spring:
  profiles:
    active: dev
  messages:
    basename: messages/messages
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 10
  #        generate_statistics: true
  datasource:
    url: jdbc:h2:mem:widget_organizer
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
